stages:
    - test
test:
    stage: test
    script:
        - git clone https://github.com/yosrajabri/gitlab-integration.git
        - cd gitlab-integration
        - python gitlab-integration/tp1.py
